### ISSUE TITLE
Refactor existing repo to monorepo using Lerna

### ISSUE THREAD

**Issue by musangowope** [laws-africa/law-widgets#157]
- [ ] Setup Lerna workspace
- [ ] Use this [package](https://www.npmjs.com/package/@nxext/stencil) to create a stencil workspace and migrate our existing components to that workspace
- [ ] Generate react workspace from stencil components `nx g @nxext/stencil:add-outputtarget core-components --outputType='react'`
- [ ] Generate storybook stories from stencil components using plugins

**Comment by longhotsummer** [comment]
For now, I think we only want to bring in [indigo-web](https://github.com/laws-africa/indigo-web). The stenciljs/ionic team do seem to indicate that you can publish to npm separately.

**Comment by longhotsummer** [comment]
Can we close this?
